### ISSUE TITLE
Configuring XBackBone to use Postfix

### ISSUE THREAD

**Issue by GabrielSerealia** [SergiX44/XBackBone#444]
Hello, I'm trying to get my docker install of XBackBone to use Postfix.

I've added a working postfix docker container to the docker-compose.yml and configured it with the correct information. I am able to send email through the postfix docker container as I've tested it with 2 other apps configured to route mail through it.

When I try to send a recovery email through the login page of XBackBone I do not receive anything. I have also tried going through the issue history but was unable to find anything for this.

I've also tried using the LAN address of the docker host 10.0.0.107 in addition to the postfix container name.
Postfix is configured to listen on 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16

php-local.ini:
```INI
; Edit this file to override php.ini directives and restart the container

date.timezone = America/Toronto
upload_max_filesize = 25M
post_max_size = 25M
[mail function]
SMTP=postfix
smtp_port=2525
```

docker-compose.yml
```YML
version: "2.1"
services:
  xbackbone:
    image: lscr.io/linuxserver/xbackbone
    container_name: xbackbone
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /opt/xbackbone/config:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  postfix:
    image: juanluisbaptiste/postfix:latest
    container_name: postfix
    ports:
      - "2525:25"
    environment:
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT:587
      - SMTP_USERNAME=USER@MY_DOMAIN.ca
      - SMTP_PASSWORD=MY_PASSWORD
      - SERVER_HOSTNAME=MY_DOMAIN.ca
      - OVERWRITE_FROM:ALIAS@MY_DOMAIN.ca
      - DEBUG=no
    restart: unless-stopped
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
```
![recovery](https://i.serealia.ca/puGE3/JupuviBu03.png/raw.png)
