### ISSUE TITLE
CSS loading fails when using 

### ISSUE THREAD

**Issue by Crown0815** [SergiX44/XBackBone#514]
**System Info**

- docker-compose.yml file:
```yaml
services:
  xbackbone:
    image: lscr.io/linuxserver/xbackbone:latest
    container_name: xbackbone
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /vagrant/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
```

- Vagrantfile: 
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  
  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always"
  
  config.vm.network :forwarded_port, guest: 80, host: 4567
end
```

+ PHP Version:
+ XBackBone Version: lscr.io/linuxserver/xbackbone:latest
+ Webserver: Nginx
+ Database backend: SQLite

**Describe the bug**
Using vagrant and the provided docker image leads to an instance that does not load any css. 

In the nginx error.log file there are two access errors for the css files

```log
2023/01/20 13:12:47 [alert] 239#239: *9 sendfile() failed (22: Invalid argument) while sending response to client, client: 10.0.2.2, server: _, request: "GET /static/bootstrap/css/bootstrap.min.css?1674216767 HTTP/1.1", host: "127.0.0.1:4567", referrer: "http://127.0.0.1:4567/install/"
2023/01/20 13:12:47 [alert] 238#238: *14 sendfile() failed (22: Invalid argument) while sending response to client, client: 10.0.2.2, server: _, request: "GET /static/bootstrap/js/bootstrap.bundle.min.js?1674216767 HTTP/1.1", host: "127.0.0.1:4567", referrer: "http://127.0.0.1:4567/install/"
```

Unfortunately, I am not familiar with PHP or nginx; therefore, I am unable to determine what the issue is. The user access (PUID:1000 and PGID:1000) is configured to the main user (i.e., vagrant). 

**To Reproduce**
1. Install [vagrant](https://developer.hashicorp.com/vagrant/docs/installation) and the [vagrant docker-compose plugin](https://github.com/leighmcculloch/vagrant-docker-compose).
2. Create a folder with the aforementioned `Vagrantfile`, `docker-compose.yml` file, and an empty folder called `config`.
3. Start vagrant by calling `vagrant up` from the created folder
4. Enter the virtual machine using `vagrant ssh`, navigate to the `/vagrant` folder and call `docker compose up`
5. Go to `127.0.0.1:4567` in your browser
6.  The page is only HTML without CSS and the error message can be seen in `config\log\nginx\error.log`

**Expected behavior**
No error message and properly styled HTML

**Screenshots**
![image](https://user-images.githubusercontent.com/36126706/213693729-7cddee52-2b1a-438f-94df-a394aaef20be.png)

**Logs**
[access.log](https://github.com/SergiX44/XBackBone/files/10466249/access.log)
[error.log](https://github.com/SergiX44/XBackBone/files/10466250/error.log)
