### ISSUE TITLE
Password Recovery/Reset

### ISSUE THREAD

**Issue by squidds** [SergiX44/XBackBone#519]
Hi, 

I am using LinuxServer's docker-compose for XbackBone. It works great. But Somehow I have gotten locked out of my account. Is there an incorrect password attempts lock? I had the password saved into my bitwarden instance, and was using that to log in every time. 

There isn't a ton of documentation from LinuxServer on getting email set up, so I am not able to use that to recover my password. 

XBackBone works great and I am hoping I don't need to lose all of my uploads. I can re-upload them, I have them saved, but it's a pretty good amount of data. It would be a last resort. 

Thank you. 

```
version: 3
 services:
  xbackbone:
    image: ghcr.io/linuxserver/xbackbone
    container_name: xbackbone
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./xbackbone:/config
#    ports:
#      - 8087:80
#      - 4443:443
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xbackbone.entrypoints=http"
      - "traefik.http.routers.xbackbone.rule=Host(`i.domain.name`)"
      - "traefik.http.middlewares.xbackbone-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.xbackbone.middlewares=xbackbone-https-redirect"
      - "traefik.http.routers.xbackbone-secure.entrypoints=https"
      - "traefik.http.routers.xbackbone-secure.rule=Host(`i.domain.name`)"
      - "traefik.http.routers.xbackbone-secure.tls=true"
      - "traefik.http.routers.xbackbone-secure.service=xbackbone"
      - "traefik.http.services.xbackbone.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

```

for reference
